import numpy as np
import pandas as pd
from pathlib import Path
from scipy.optimize import minimize


class MarkowitzOptimizer:
    """
    Portfolio optimization using Modern Portfolio Theory.
    """

    def __init__(
        self,
        returns_file="data/processed/returns.csv",
        risk_free_rate=0.065
    ):
        self.returns_file = Path(returns_file)
        self.risk_free_rate = risk_free_rate
        self.trading_days = 252

        self.returns = None
        self.expected_returns = None
        self.covariance_matrix = None

    def load_returns(self):
        """
        Load daily returns generated by the data loader.
        """

        self.returns = pd.read_csv(
            self.returns_file,
            parse_dates=["date"]
        )

        print("Returns loaded successfully.")
        print(self.returns.head())

    def calculate_expected_returns(self):
       """
       Calculate annual expected returns for each stock.
      """

       self.expected_returns = (
           self.returns.iloc[:, 1:]
           .mean()
           * self.trading_days
        )

       print("\nExpected Annual Returns")
       print("-" * 35)
       print(self.expected_returns)

    def calculate_covariance_matrix(self):
       """
       Calculate the annualized covariance matrix.
       """

       self.covariance_matrix = (
        self.returns.iloc[:, 1:]
        .cov()
        * self.trading_days
    )

       print("\nAnnualized Covariance Matrix")
       print("-" * 35)
       print(self.covariance_matrix)

if __name__ == "__main__":

    optimizer = MarkowitzOptimizer()

    optimizer.load_returns()

    optimizer.calculate_expected_returns()

    optimizer.calculate_covariance_matrix()