import numpy as np
import pandas as pd
from pathlib import Path
from requests.packages import target
from scipy.optimize import minimize


class RiskParityOptimizer:
    """
    Portfolio optimization using Risk Parity.
    """

    def __init__(
        self,
        returns_file="data/processed/returns.csv"
    ):

        self.returns_file = Path(returns_file)
        self.trading_days = 252

        self.returns = None
        self.covariance_matrix = None

    def load_returns(self):
        """
        Load daily returns generated by the data loader.
        """

        self.returns = pd.read_csv(
            self.returns_file,
            parse_dates=["date"]
        )

        print("Returns loaded successfully.")

        print(
            f"Number of trading days: "
            f"{len(self.returns)}"
        )

        print(
            f"Number of assets: "
            f"{len(self.returns.columns) - 1}"
        )
    def calculate_covariance_matrix(self):
        """
        Calculate the annualized covariance matrix
        of asset returns.
        """

        asset_returns = self.returns.iloc[:, 1:]

        self.covariance_matrix = (
        asset_returns.cov() * self.trading_days)

        print("\nAnnualized Covariance Matrix")
        print("-" * 40)
        print(self.covariance_matrix)
    def portfolio_risk(self, weights):
        """
        Calculate annualized portfolio volatility.
        """
        return np.sqrt(
        weights.T
        @ self.covariance_matrix.values
        @ weights)
    def risk_contributions(self, weights):
        """
        Calculate each asset's contribution to total portfolio risk.
        """

        covariance = self.covariance_matrix.values

        portfolio_risk = self.portfolio_risk(weights)

        marginal_contribution = (
        covariance @ weights
    )

        component_contribution = (
        weights * marginal_contribution
    )

        risk_contribution = (
        component_contribution / portfolio_risk
    )

        return risk_contribution
    def risk_parity_objective(self, weights):
        """
        Objective function for Risk Parity optimization.

        The goal is to make each asset's risk contribution
        as close as possible to an equal target.
        """

        contributions = self.risk_contributions(weights)

        total_contribution = contributions.sum()

        risk_contribution_percent = (
        contributions / total_contribution
    )

        num_assets = len(weights)

        target = np.array(
        [1 / num_assets] * num_assets
    )

        squared_difference = (
        risk_contribution_percent - target
    ) ** 2

        return squared_difference.sum()
    def optimize(self):
        """
        Find the Risk Parity portfolio weights.
        """

        num_assets = len(
        self.returns.columns
    ) - 1

        initial_weights = np.array(
        [1 / num_assets] * num_assets
    )

        constraints = {
        "type": "eq",
        "fun": lambda weights:
            np.sum(weights) - 1
    }

        bounds = tuple(
        (0, 1)
        for _ in range(num_assets)
    )

        result = minimize(
        fun=self.risk_parity_objective,
        x0=initial_weights,
        method="SLSQP",
        bounds=bounds,
        constraints=constraints
    )

        return result
    def portfolio_return(self, weights):
        """
        Calculate annualized expected portfolio return.
        """
        expected_returns = (
        self.returns.iloc[:, 1:]
        .mean()
        * self.trading_days
    )

        return np.dot(
        weights,
        expected_returns.values
    )
    def portfolio_sharpe_ratio(self, weights):
        """
        Calculate annualized portfolio Sharpe ratio.
        """

        portfolio_return = self.portfolio_return(weights)

        portfolio_risk = self.portfolio_risk(weights)

        risk_free_rate = 0.065

        if portfolio_risk == 0:
            return 0.0

        return (
        portfolio_return - risk_free_rate
    ) / portfolio_risk
    def portfolio_returns(self, weights):
        """
        Calculate the historical daily returns
        of the portfolio.
        """

        asset_returns = self.returns.iloc[:, 1:]

        return asset_returns @ weights
    def portfolio_max_drawdown(self, weights):
        """
        Calculate maximum historical drawdown
        of the portfolio.
        """

        portfolio_returns = self.portfolio_returns(weights)

        cumulative_returns = (
        1 + portfolio_returns
    ).cumprod()

        running_max = cumulative_returns.cummax()

        drawdown = (
        cumulative_returns - running_max
    ) / running_max

        return drawdown.min()

if __name__ == "__main__":

    optimizer = RiskParityOptimizer()

    optimizer.load_returns()

    optimizer.calculate_covariance_matrix()

    result = optimizer.optimize()

    print("\nRisk Parity Optimization")
    print("-" * 40)

    print(
        f"Optimization Success: "
        f"{result.success}"
    )

    assets = optimizer.returns.columns[1:]

    print("\nOptimal Weights")
    print("-" * 40)

    for asset, weight in zip(
        assets,
        result.x
    ):
        print(
            f"{asset:<12} "
            f"{weight:.4%}"
        )

    print("\nWeight Sum")
    print("-" * 40)

    print(
        f"{result.x.sum():.4%}"
    )

    risk_contributions = optimizer.risk_contributions(
        result.x
    )

    print("\nRisk Contributions")
    print("-" * 40)

    for asset, contribution in zip(
        assets,
        risk_contributions
    ):

        print(
            f"{asset:<12} "
            f"{contribution:.4%}"
        )

    print("\nTotal Risk Contribution")
    print("-" * 40)

    print(
        f"{risk_contributions.sum():.4%}"
    )
    portfolio_return = optimizer.portfolio_return(
    result.x)

    portfolio_risk = optimizer.portfolio_risk(
    result.x)

    sharpe = optimizer.portfolio_sharpe_ratio(
    result.x
)

    print("\nRisk Parity Portfolio Performance")
    print("-" * 40)

    print(
    f"Expected Annual Return : "
    f"{portfolio_return:.2%}"
)

    print(
    f"Annual Volatility      : "
    f"{portfolio_risk:.2%}"
)

    print(
    f"Sharpe Ratio           : "
    f"{sharpe:.3f}"
)
    max_drawdown = optimizer.portfolio_max_drawdown(
    result.x
)

    print(
    f"Maximum Drawdown      : "
    f"{max_drawdown:.2%}"
)